# Generated by Django 5.0.6 on 2024-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аватарка'),
        ),
    ]
