# Generated by Django 5.0.6 on 2024-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='viewed',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
