# Generated by Django 5.0.6 on 2024-07-21 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-z\\-]*$', 'Только безопасные символы')], verbose_name='slug'),
        ),
    ]
