# Generated by Django 5.0.6 on 2024-08-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название категории')),
                ('description', models.TextField(verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название продукта')),
                ('description', models.TextField(verbose_name='описание продукта')),
                ('preview', models.ImageField(upload_to='media/', verbose_name='превью продукта')),
                ('price', models.IntegerField(verbose_name='цена продукта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания продукта')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата редактирования продукта')),
                ('manufactured_at', models.DateField(null=True, verbose_name='Дата производства продукта')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='категория продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='номер версии')),
                ('version_name', models.CharField(max_length=255, verbose_name='название версии')),
                ('current_version', models.BooleanField(verbose_name='признак текущей версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('product', 'version', 'current_version'),
            },
        ),
    ]
