# Generated by Django 5.0.6 on 2024-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название продукта')),
                ('description', models.TextField(verbose_name='описание продукта')),
                ('preview', models.ImageField(upload_to='previews/', verbose_name='превью продукта')),
                ('category', models.SmallIntegerField(verbose_name='категория продукта')),
                ('price', models.IntegerField(verbose_name='цена продукта')),
                ('creation_date', models.DateField(verbose_name='дата создания продукта')),
                ('last_edit_date', models.DateField(verbose_name='дата редактирования продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name', 'category'),
            },
        ),
    ]
