# Generated by Django 4.2 on 2024-08-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category'), 'permissions': [('set_published_status', 'Can (un)publish product'), ('change_description', 'Can change product description'), ('change_category', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
