# Generated by Django 5.0.6 on 2024-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_manufactured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(null=True, verbose_name='Дата производства продукта'),
        ),
    ]
