# Generated by Django 5.0.6 on 2024-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_manufactured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(upload_to='media/', verbose_name='превью продукта'),
        ),
    ]
